# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HW2_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DockWidget(object):
    def setupUi(self, DockWidget):
        DockWidget.setObjectName("DockWidget")
        DockWidget.resize(582, 542)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.groupBox = QtWidgets.QGroupBox(self.dockWidgetContents)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 261, 231))
        self.groupBox.setObjectName("groupBox")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(30, 40, 201, 51))
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(30, 160, 211, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(30, 188, 211, 16))
        self.label_3.setObjectName("label_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(30, 90, 201, 51))
        self.pushButton_2.setObjectName("pushButton_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.dockWidgetContents)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 260, 541, 231))
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButton_2_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_2_2.setGeometry(QtCore.QRect(30, 100, 201, 51))
        self.pushButton_2_2.setObjectName("pushButton_2_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_3.setGeometry(QtCore.QRect(260, 40, 281, 161))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setGeometry(QtCore.QRect(40, 30, 91, 16))
        self.label.setObjectName("label")
        self.spinBox = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBox.setGeometry(QtCore.QRect(40, 60, 81, 24))
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(15)
        self.spinBox.setObjectName("spinBox")
        self.pushButton_2_3 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_2_3.setGeometry(QtCore.QRect(30, 100, 201, 51))
        self.pushButton_2_3.setObjectName("pushButton_2_3")
        self.pushButton_2_4 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_2_4.setGeometry(QtCore.QRect(30, 160, 201, 51))
        self.pushButton_2_4.setObjectName("pushButton_2_4")
        self.pushButton_2_1 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_2_1.setGeometry(QtCore.QRect(30, 40, 201, 51))
        self.pushButton_2_1.setObjectName("pushButton_2_1")
        self.groupBox_4 = QtWidgets.QGroupBox(self.dockWidgetContents)
        self.groupBox_4.setGeometry(QtCore.QRect(290, 10, 271, 111))
        self.groupBox_4.setObjectName("groupBox_4")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_3.setGeometry(QtCore.QRect(30, 40, 201, 51))
        self.pushButton_3.setObjectName("pushButton_3")
        self.groupBox_5 = QtWidgets.QGroupBox(self.dockWidgetContents)
        self.groupBox_5.setGeometry(QtCore.QRect(290, 130, 271, 111))
        self.groupBox_5.setObjectName("groupBox_5")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_4.setGeometry(QtCore.QRect(30, 40, 201, 51))
        self.pushButton_4.setObjectName("pushButton_4")
        DockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(DockWidget)
        QtCore.QMetaObject.connectSlotsByName(DockWidget)

    def retranslateUi(self, DockWidget):
        _translate = QtCore.QCoreApplication.translate
        DockWidget.setWindowTitle(_translate("DockWidget", "DockWidget"))
        self.groupBox.setTitle(_translate("DockWidget", "1. Find Contour"))
        self.pushButton.setText(_translate("DockWidget", "1.1 Draw Contour"))
        self.label_2.setText(_translate("DockWidget", "There are __ coins in coin01.jpg"))
        self.label_3.setText(_translate("DockWidget", "There are __ coins in coin02.jpg"))
        self.pushButton_2.setText(_translate("DockWidget", "1.2 Count Coins"))
        self.groupBox_2.setTitle(_translate("DockWidget", "2. Calibration"))
        self.pushButton_2_2.setText(_translate("DockWidget", "2.2 Find Intrinsic"))
        self.groupBox_3.setTitle(_translate("DockWidget", "2.3 Find Extrinsic"))
        self.label.setText(_translate("DockWidget", "Select image"))
        self.pushButton_2_3.setText(_translate("DockWidget", "2.3 Find Extrinsic"))
        self.pushButton_2_4.setText(_translate("DockWidget", "2.4 Find Distortion"))
        self.pushButton_2_1.setText(_translate("DockWidget", "2.1 Find Corners"))
        self.groupBox_4.setTitle(_translate("DockWidget", "3. Augmented Reality"))
        self.pushButton_3.setText(_translate("DockWidget", "3.1 Augmented Reality"))
        self.groupBox_5.setTitle(_translate("DockWidget", "4. Stereo Disparity Map"))
        self.pushButton_4.setText(_translate("DockWidget", "4.1 Stereo Disparity"))
